// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALG499BSf7hIbHgkENUEXGGnepRnEdZg4',
    appId: '1:540766714351:web:9734cd021d5a253eef5e1a',
    messagingSenderId: '540766714351',
    projectId: 'ifigth-f14bf',
    authDomain: 'ifigth-f14bf.firebaseapp.com',
    storageBucket: 'ifigth-f14bf.firebasestorage.app',
    measurementId: 'G-P6BNBVZPKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqKaMOBDKbgiC2R60oW8qtHRI2L8A-ntM',
    appId: '1:540766714351:android:71623fee964f96ccef5e1a',
    messagingSenderId: '540766714351',
    projectId: 'ifigth-f14bf',
    storageBucket: 'ifigth-f14bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETVDDfVQPbEY9k1EnpbOFHQ7BYvBCD1c',
    appId: '1:540766714351:ios:760df6112b6c4937ef5e1a',
    messagingSenderId: '540766714351',
    projectId: 'ifigth-f14bf',
    storageBucket: 'ifigth-f14bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAETVDDfVQPbEY9k1EnpbOFHQ7BYvBCD1c',
    appId: '1:540766714351:ios:760df6112b6c4937ef5e1a',
    messagingSenderId: '540766714351',
    projectId: 'ifigth-f14bf',
    storageBucket: 'ifigth-f14bf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALG499BSf7hIbHgkENUEXGGnepRnEdZg4',
    appId: '1:540766714351:web:ae2aeab2b40e3c8eef5e1a',
    messagingSenderId: '540766714351',
    projectId: 'ifigth-f14bf',
    authDomain: 'ifigth-f14bf.firebaseapp.com',
    storageBucket: 'ifigth-f14bf.firebasestorage.app',
    measurementId: 'G-1HPDTV18VY',
  );
}
